### ISSUE TITLE
Errors installing the project

### ISSUE THREAD

**Issue by StuartFlutter** [Peersyst/ckbull-mobile#329]
Cloning the repo and trying to build locally (so i can offer input).

I get:

```404 Not Found - GET https://registry.npmjs.org/@peersyst%2freact-hooks - Not found
npm ERR! 404 
npm ERR! 404  '@peersyst/react-hooks@1.2.0' is not in this registry.
```

Where is "@peersyst%2freact-hooks " coming from?

**Comment by 57u** [comment]
This was resolved by the team re-instating the relevant npm packages and making them available to us again. 

Closing issue.
