### ISSUE TITLE
Redesign: Auth - SetName Screen

### ISSUE THREAD

**Issue by JordiParraCrespo** [Peersyst/ckbull-mobile#402]
- Check in the current CKBull app the flow to add a name to an account and add it to the auth flow
- https://github.com/Peersyst/ckbull-mobile/blob/main/src/module/wallet/screen/SetWalletNameScreen.tsx
- https://github.com/Peersyst/ckbull-mobile/blob/main/src/module/wallet/navigator/CreateWalletNavigatorGroup.tsx
- https://github.com/Peersyst/ckbull-mobile/blob/main/src/module/wallet/navigator/ImportWalletNavigatorGroup.tsx

**Comment by silvap-javier** [comment]
Esto es para la tab de create wallet que falta
